"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { LISTING_CONFIRMATIONS, LISTING_EXCHANGES, LISTING_STATUSES, LISTING_TYPES } from "@/lib/listings/contracts";
import { useI18n } from "@/components/i18n/LocaleProvider";

type Analysis = { summary: string; explanation: string; impact: string; confidence: string; model: string; totalTokens: number | null };
type Source = { id: string; exchange: string; name: string; lastSuccessAt: string | null; lastError: string | null };
type Event = { id: string; exchange: string; asset: string; symbol: string; title: string; type: string; status: string; confirmation: string; announcedAt: string; tradingStartsAt: string | null; pairs: string[]; alreadyTradingExchanges: string[]; currentPrice: string | null; volume24h: string | null; change24hPercent: string | null; changeSinceAnnouncement: string | null; marketUpdatedAt: string | null; aiStatus: string; aiAnalysis: Analysis | null; sources: Array<{ id: string; title: string; url: string; source: Source }>; markets: Array<{ exchange: string; pair: string; price: string | null; volume24h: string | null; change24hPercent: string | null }> };
type Translation = Record<string, string>;
type Data = { events: Event[]; sources: Source[]; refreshMinutes: number; aiConfigured: boolean; translations?: Record<string, Translation> };
type Filters = { period: "24h" | "7d" | "30d"; exchange: string; asset: string; type: string; status: string; confirmation: string };

const TYPE_LABELS: Record<string, string> = { NEW_LISTING: "Nova listagem", DELISTING: "Delistagem", NEW_TRADING_PAIR: "Novo par", PAIR_REMOVAL: "Remoção de par", PRE_MARKET: "Pré-mercado", LAUNCHPOOL: "Launchpool", LAUNCHPAD: "Launchpad", AIRDROP: "Airdrop", OTHER: "Outro" };
const STATUS_LABELS: Record<string, string> = { ANNOUNCED: "Anunciado", UPCOMING: "Próxima", LIVE: "Negociação ativa", COMPLETED: "Concluído", DELISTING_SCHEDULED: "Delistagem agendada", DELISTED: "Delistado", UNCONFIRMED: "Não confirmado" };
const fmtDate = (value: string | null) => value ? new Date(value).toLocaleString("pt-PT", { timeZone: "UTC", dateStyle: "medium", timeStyle: "short" }) + " UTC" : "Não informado";
const money = (value: string | null) => value && Number.isFinite(Number(value)) ? Number(value).toLocaleString("en-US", { style: "currency", currency: "USD", maximumSignificantDigits: 8 }) : "Indisponível";
const number = (value: string | null) => value && Number.isFinite(Number(value)) ? Number(value).toLocaleString("pt-PT", { maximumFractionDigits: 2 }) : "Indisponível";

async function api<T>(url: string, init?: RequestInit): Promise<T> {
  const response = await fetch(url, { cache: "no-store", ...init });
  const body = await response.json().catch(() => ({})) as { error?: string };
  if (!response.ok) throw Object.assign(new Error(body.error ?? "INTERNAL_ERROR"), { status: response.status });
  return body as T;
}

function ListingCard({ event, translated = {} }: { event: Event; translated?: Translation }) {
  const { locale, t } = useI18n();
  const typeLabels = locale === "en" ? { NEW_LISTING: "New listing", DELISTING: "Delisting", NEW_TRADING_PAIR: "New pair", PAIR_REMOVAL: "Pair removal", PRE_MARKET: "Pre-market", LAUNCHPOOL: "Launchpool", LAUNCHPAD: "Launchpad", AIRDROP: "Airdrop", OTHER: "Other" } : locale === "es" ? { NEW_LISTING: "Nuevo listado", DELISTING: "Retiro", NEW_TRADING_PAIR: "Nuevo par", PAIR_REMOVAL: "Retiro de par", PRE_MARKET: "Premercado", LAUNCHPOOL: "Launchpool", LAUNCHPAD: "Launchpad", AIRDROP: "Airdrop", OTHER: "Otro" } : TYPE_LABELS;
  const statusLabels = locale === "en" ? { ANNOUNCED: "Announced", UPCOMING: "Upcoming", LIVE: "Trading now", COMPLETED: "Completed", DELISTING_SCHEDULED: "Delisting scheduled", DELISTED: "Delisted", UNCONFIRMED: "Unconfirmed" } : locale === "es" ? { ANNOUNCED: "Anunciado", UPCOMING: "Próximo", LIVE: "Negociación activa", COMPLETED: "Completado", DELISTING_SCHEDULED: "Retiro programado", DELISTED: "Retirado", UNCONFIRMED: "No confirmado" } : STATUS_LABELS;
  const aiLabel = event.aiAnalysis ? t("status.analyzed") : event.aiStatus === "ERROR" ? t("status.aiError") : t("status.awaitingAi");
  const movement = event.changeSinceAnnouncement === null ? t("common.unavailable") : `${Number(event.changeSinceAnnouncement) >= 0 ? "+" : ""}${number(event.changeSinceAnnouncement)}%`;
  return <article className="rc-listing-card">
    <header><div><span className="rc-listing-exchange">{event.exchange}</span><span className="rc-listing-confirmation">{translated.confirmation || event.confirmation}</span></div><span className={`rc-listing-status rc-listing-status--${event.status.toLowerCase()}`}>{translated.status || statusLabels[event.status as keyof typeof statusLabels] || event.status}</span></header>
    <div className="rc-listing-symbol"><strong>{event.asset}</strong><span>{event.pairs.length ? event.pairs.join(" · ") : event.symbol}</span></div>
    <h3>{translated.title || event.title}</h3>
    <p className="rc-listing-type">{translated.type || typeLabels[event.type as keyof typeof typeLabels] || event.type}</p>
    {event.confirmation.includes("RUMOR") && <p className="rc-listing-warning">{locale === "en" ? "Possible listing mentioned by a secondary source — not confirmed by the exchange." : locale === "es" ? "Posible listado mencionado por una fuente secundaria — no confirmado por el exchange." : "Possível listagem mencionada por fonte secundária — não confirmada pela exchange."}</p>}
    <div className="rc-listing-timeline"><div><span>{t("listings.announcement")}</span><strong>{fmtDate(event.announcedAt)}</strong></div><i>→</i><div><span>{t("listings.expected")}</span><strong>{fmtDate(event.tradingStartsAt)}</strong></div><i>→</i><div><span>{t("listings.status").toUpperCase()}</span><strong>{translated.status || statusLabels[event.status as keyof typeof statusLabels] || event.status}</strong></div></div>
    <div className="rc-listing-market"><div><span>{t("listings.currentPrice")}</span><strong>{money(event.currentPrice)}</strong></div><div><span>{t("listings.volume")}</span><strong>{event.volume24h ? `$${number(event.volume24h)}` : t("common.unavailable")}</strong></div><div><span>{t("listings.change")}</span><strong>{event.change24hPercent === null ? t("common.unavailable") : `${number(event.change24hPercent)}%`}</strong></div><div><span>{t("listings.since")}</span><strong>{movement}</strong></div></div>
    <div className="rc-listing-venues"><span>{t("listings.already")}</span><p>{event.alreadyTradingExchanges.length ? event.alreadyTradingExchanges.join(" · ") : t("common.unavailable")}</p></div>
    <div className="rc-listing-ai"><strong>{aiLabel}</strong>{event.aiAnalysis ? <><p>{translated.summary || event.aiAnalysis.summary}</p><small>{translated.explanation || event.aiAnalysis.explanation} · {translated.impact || event.aiAnalysis.impact} · {translated.confidence || event.aiAnalysis.confidence}</small></> : <p>{locale === "en" ? "Optional analysis has not been requested yet." : locale === "es" ? "El análisis opcional aún no se ha solicitado." : "A análise opcional ainda não foi solicitada."}</p>}</div>
    <footer><span>{event.sources.length} {locale === "en" ? "official reference(s)" : locale === "es" ? "referencia(s) oficial(es)" : "referência(s) oficial(is)"}</span>{event.sources.map((source) => <a key={source.id} href={source.url} target="_blank" rel="noopener noreferrer">{source.source.name} ↗</a>)}</footer>
  </article>;
}

export default function ListingRadarClient() {
  const { locale, t } = useI18n();
  const [filters, setFilters] = useState<Filters>({ period: "30d", exchange: "", asset: "", type: "", status: "", confirmation: "" });
  const [data, setData] = useState<Data>({ events: [], sources: [], refreshMinutes: 30, aiConfigured: false });
  const [loading, setLoading] = useState(true), [refreshing, setRefreshing] = useState(false), [analyzing, setAnalyzing] = useState(false), [unauthorized, setUnauthorized] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const load = useCallback(async (current: Filters) => { const params = new URLSearchParams({ period: current.period, locale }); Object.entries(current).forEach(([key, value]) => key !== "period" && value && params.set(key, value)); try { setData(await api<Data>(`/api/listagens/events?${params}`)); setUnauthorized(false); } catch (error) { if (typeof error === "object" && error && "status" in error && error.status === 401) setUnauthorized(true); setMessage(locale === "en" ? "Could not load listings." : locale === "es" ? "No se pudieron cargar los listados." : "Não foi possível carregar as listagens."); } finally { setLoading(false); } }, [locale]);
  useEffect(() => { const timer = window.setTimeout(() => void load(filters), 0); return () => window.clearTimeout(timer); }, [filters, load]);
  function update(key: keyof Filters, value: string) { setLoading(true); setMessage(null); setFilters((current) => ({ ...current, [key]: value })); }
  async function refresh() { setRefreshing(true); setMessage(null); try { const result = await api<{ collection: { inserted: number; sources: Array<{ ok: boolean }>; marketProvidersUnavailable: string[] } }>("/api/listagens/refresh", { method: "POST", headers: { "content-type": "application/json", "x-radarcrypto-csrf": "1" }, body: JSON.stringify({ analyzeWithAi: false }) }); setMessage(`${result.collection.inserted} evento(s) novo(s), ${result.collection.sources.filter((source) => source.ok).length} fonte(s) oficiais disponíveis. OpenAI não foi chamada.`); await load(filters); } catch (error) { setMessage(error instanceof Error && error.message === "LISTINGS_REFRESH_RATE_LIMITED" ? `Atualização disponível a cada ${data.refreshMinutes} minutos.` : "A atualização falhou; o histórico existente permanece disponível."); } finally { setRefreshing(false); } }
  async function analyze() { setAnalyzing(true); setMessage(null); try { const result = await api<{ ai: { configured: boolean; analyzed: number; calls: number; usage: { totalTokens: number | null } | null; model?: string; error?: string } }>("/api/listagens/analyze", { method: "POST", headers: { "x-radarcrypto-csrf": "1" } }); setMessage(!result.ai.configured ? "OpenAI não configurada; as listagens permanecem disponíveis." : result.ai.error ? `A análise falhou (${result.ai.error}); será possível tentar novamente.` : `${result.ai.analyzed} evento(s), ${result.ai.calls} chamada(s), ${result.ai.usage?.totalTokens ?? 0} token(s), modelo ${result.ai.model ?? "não utilizado"}.`); await load(filters); } catch { setMessage("A análise IA falhou; as listagens permanecem disponíveis."); } finally { setAnalyzing(false); } }
  async function translateMissing() { if (data.events.length === 0) return; setAnalyzing(true); setMessage(null); try { const result = await api<{ generated: number }>("/api/translations/ensure", { method: "POST", headers: { "content-type": "application/json", "x-radarcrypto-csrf": "1" }, body: JSON.stringify({ entityType: "LISTING_EVENT", ids: data.events.slice(0, 20).map((event) => event.id), locale }) }); setMessage(locale === "en" ? `${result.generated} missing translation(s) generated and cached.` : locale === "es" ? `${result.generated} traducción(es) faltante(s) generada(s) y guardada(s).` : `${result.generated} tradução(ões) ausente(s) gerada(s) e armazenada(s).`); await load(filters); } catch { setMessage(locale === "en" ? "Translations could not be generated; original content remains available." : locale === "es" ? "No se pudieron generar las traducciones; el contenido original sigue disponible." : "Não foi possível gerar as traduções; o conteúdo original continua disponível."); } finally { setAnalyzing(false); } }
  const sections = useMemo(() => ({ recent: data.events.slice(0, 6), upcoming: data.events.filter((event) => event.status === "UPCOMING"), live: data.events.filter((event) => event.status === "LIVE"), delistings: data.events.filter((event) => ["DELISTING", "PAIR_REMOVAL"].includes(event.type)) }), [data.events]);
  if (unauthorized) return <section className="rc-radar-auth"><p>{locale === "en" ? "Listings Radar requires internal authentication." : locale === "es" ? "Radar de Listados requiere autenticación interna." : "Radar de Listagens exige autenticação interna."}</p><Link href="/login" className="rc-home-cta rc-home-cta--primary">{t("actions.enter")}</Link></section>;
  return <main className="rc-listings-page"><header className="rc-listings-hero"><p className="rc-section-kicker">{locale === "en" ? "OFFICIAL SOURCES · PUBLIC MARKET" : locale === "es" ? "FUENTES OFICIALES · MERCADO PÚBLICO" : "FONTES OFICIAIS · MERCADO PÚBLICO"}</p><h1>{t("listings.title")}</h1><p>{t("listings.description")}</p><small>{locale === "en" ? "Information module. It does not execute orders or use private credentials." : locale === "es" ? "Módulo informativo. No ejecuta órdenes ni utiliza credenciales privadas." : "Módulo informativo. Não executa ordens nem utiliza credenciais privadas."}</small></header>
    <section className="rc-listings-toolbar"><div><span>{t("news.period")}</span>{(["24h", "7d", "30d"] as const).map((period) => <button key={period} className={filters.period === period ? "is-active" : ""} onClick={() => update("period", period)}>{period}</button>)}</div><label>Exchange<select value={filters.exchange} onChange={(e) => update("exchange", e.target.value)}><option value="">{t("common.allF")}</option>{LISTING_EXCHANGES.map((value) => <option key={value}>{value}</option>)}</select></label><label>{t("news.asset")}<input value={filters.asset} maxLength={15} onChange={(e) => update("asset", e.target.value.toUpperCase().replace(/[^A-Z0-9]/g, ""))} placeholder="BTC" /></label><label>{t("listings.type")}<select value={filters.type} onChange={(e) => update("type", e.target.value)}><option value="">{t("common.all")}</option>{LISTING_TYPES.map((value) => <option key={value} value={value}>{value}</option>)}</select></label><label>{t("listings.status")}<select value={filters.status} onChange={(e) => update("status", e.target.value)}><option value="">{t("common.all")}</option>{LISTING_STATUSES.map((value) => <option key={value} value={value}>{value}</option>)}</select></label><label>{t("listings.confirmation")}<select value={filters.confirmation} onChange={(e) => update("confirmation", e.target.value)}><option value="">{t("common.allF")}</option>{LISTING_CONFIRMATIONS.map((value) => <option key={value}>{value}</option>)}</select></label><div className="rc-listings-actions"><button onClick={refresh} disabled={refreshing || analyzing}>{refreshing ? t("news.refreshing") : t("listings.refresh")}</button><div><button onClick={analyze} disabled={refreshing || analyzing || !data.aiConfigured}>{analyzing ? t("news.analyzing") : t("listings.analyze")}</button><small>{t("news.aiCost")}</small></div><button onClick={translateMissing} disabled={refreshing || analyzing || data.events.length === 0}>{locale === "en" ? "TRANSLATE MISSING" : locale === "es" ? "TRADUCIR PENDIENTES" : "TRADUZIR PENDENTES"}</button></div></section>
    {message && <div className="rc-radar-alert" role="status">{message}</div>}
    {loading ? <div className="rc-radar-empty">{t("actions.loading")}</div> : ([{ key: "recent", title: t("listings.recent") }, { key: "upcoming", title: t("listings.upcoming") }, { key: "live", title: t("listings.live") }, { key: "delistings", title: t("listings.delistings") }] as const).map(({ key, title }) => <section key={key} className="rc-listings-section"><div className="rc-section-heading"><div><p className="rc-section-kicker">{locale === "en" ? "MONITORING" : locale === "es" ? "MONITOREO" : "MONITORAMENTO"}</p><h2>{title}</h2></div><p>{sections[key].length} evento(s).</p></div>{sections[key].length ? <div className="rc-listings-grid">{sections[key].map((event) => <ListingCard key={`${key}-${event.id}`} event={event} translated={data.translations?.[event.id]} />)}</div> : <div className="rc-radar-empty">{locale === "en" ? "No event in this group and filter." : locale === "es" ? "Ningún evento en este grupo y filtro." : "Nenhum evento neste grupo e filtro."}</div>}</section>)}
    <section className="rc-listing-sources"><h2>Estado das fontes de anúncios</h2><div>{data.sources.map((source) => <article key={source.id}><i className={source.lastError ? "is-error" : "is-ok"}/><strong>{source.exchange}</strong><span>{source.name}</span><small>{source.lastError ? `Indisponível: ${source.lastError}` : source.lastSuccessAt ? `Atualizada ${fmtDate(source.lastSuccessAt)}` : "Aguardando coleta"}</small></article>)}</div><p>Binance, OKX, Gate.io e MEXC participam somente do enriquecimento por APIs públicas de mercado. Não são fontes de anúncio neste Preview.</p></section>
  </main>;
}
