import type { Locale } from "./config";

export const pageContent = {
  pt: {
    plans: {
      subtitle: "Produto experimental em desenvolvimento. O modo SIM está disponível; planos pagos, Testnet e operação com dinheiro real não estão à venda nesta fase.",
      proofs: ["Fase experimental", "SIM disponível", "Sem operação Live"], start: "Começar de graça", unavailable: "Em desenvolvimento",
      items: [
        ["PRONTO PARA COMEÇAR", "Start", "€ 0,00/mês", ["Simulador spot básico", "Capital virtual de 10.000 USDT", "PNL e histórico básico", "Exportar CSV", "8 pares principais habilitados", "Gráfico de evolução mensal (equity) · em breve"]],
        ["RECOMENDADO", "Trader", "€ 9,99/mês", ["Tudo do plano Start", "Robôs automáticos (EMA Cross SIM)", "Controle de risco manual (TP/SL)", "Histórico expandido (visual e CSV)", "Troca rápida entre pares", "Painel de performance resumida · em breve"]],
        ["TURBO ACELERADO", "Pro", "€ 19,99/mês", ["Tudo do plano Trader", "Gerenciamento de risco automático", "Relatórios filtráveis e detalhados", "Estatísticas avançadas", "Exportar relatórios detalhados", "Notificações de performance · em breve"]],
        ["TUDO DESBLOQUEADO", "Elite", "€ 29,99/mês", ["Tudo do plano Pro", "Backtesting de estratégias", "Comparação de estratégias", "Histórico mensal/anual salvo", "Acesso antecipado a novidades", "Suporte prioritário e comunidade privada"]],
      ],
    },
    about: { subtitle: "Onde o aprendizado encontra a prática — sem arriscar dinheiro real, em um ambiente virtual seguro e acessível.", pills: ["Produto experimental · modo SIM", "Ferramentas para estudar o mercado"], cards: [["🔒", "Erre sem riscos", "Teste estratégias com 10.000 USDT virtuais e conheça o comportamento do mercado sem arriscar dinheiro real."], ["🧠", "Aprenda de verdade", "Pratique leitura de gráficos e desenvolva disciplina em um ambiente experimental."], ["🚀", "Evolua sempre", "Revise resultados, teste ideias e acompanhe sua performance com clareza."]], closer: "Treine hoje. Entenda amanhã. Aja com confiança." },
    contact: { lead: "Dúvidas, sugestões ou parceria? Escreva pelo formulário ou fale no WhatsApp.", sendTitle: "Envie uma mensagem", subject: "Assunto", topics: ["Dúvida", "Conta", "Outros"], name: "Seu nome", namePlaceholder: "Como devemos chamar você?", message: "Mensagem", messagePlaceholder: "Conte em detalhes como podemos ajudar…", send: "Enviar mensagem", sending: "Enviando…", whatsapp: "Chamar no WhatsApp", success: "Enviado com sucesso!", faq: "Dúvidas rápidas", questions: [["O simulador usa dados ao vivo?", "Os preços vêm de endpoints públicos da Binance; o produto permanece experimental."], ["Posso exportar meu histórico?", "Sim. O CSV representa a sessão atual do simulador manual."], ["Vocês têm WhatsApp?", "Use o botão do WhatsApp ao lado do envio do formulário."], ["Como migrar para um plano pago?", "Os planos pagos estão em desenvolvimento e ainda não aceitam contratação."]] },
    simulator: { chart: "Gráfico", fullscreen: "Tela cheia" },
  },
  en: {
    plans: { subtitle: "Experimental product in development. SIM mode is available; paid plans, Testnet and real-money operation are not for sale at this stage.", proofs: ["Experimental stage", "SIM available", "No Live operation"], start: "Start for free", unavailable: "In development", items: [["READY TO START", "Start", "€ 0.00/month", ["Basic spot simulator", "10,000 USDT virtual capital", "Basic PNL and history", "Export CSV", "8 major pairs enabled", "Monthly equity chart · coming soon"]], ["RECOMMENDED", "Trader", "€ 9.99/month", ["Everything in Start", "Automated bots (EMA Cross SIM)", "Manual risk controls (TP/SL)", "Expanded history (visual and CSV)", "Quick pair switching", "Summary performance dashboard · coming soon"]], ["ACCELERATED", "Pro", "€ 19.99/month", ["Everything in Trader", "Automatic risk management", "Filterable detailed reports", "Advanced statistics", "Export detailed reports", "Performance notifications · coming soon"]], ["EVERYTHING UNLOCKED", "Elite", "€ 29.99/month", ["Everything in Pro", "Strategy backtesting", "Strategy comparison", "Saved monthly/yearly history", "Early access to new features", "Priority support and private community"]]] },
    about: { subtitle: "Where learning meets practice — without risking real money, in a safe and accessible virtual environment.", pills: ["Experimental product · SIM mode", "Tools for studying the market"], cards: [["🔒", "Make mistakes without risk", "Test strategies with 10,000 virtual USDT and learn market behavior without risking real money."], ["🧠", "Learn by doing", "Practice chart reading and develop discipline in an experimental environment."], ["🚀", "Keep improving", "Review results, test ideas and track your performance clearly."]], closer: "Train today. Understand tomorrow. Act with confidence." },
    contact: { lead: "Questions, suggestions or partnership? Write through the form or contact us on WhatsApp.", sendTitle: "Send a message", subject: "Subject", topics: ["Question", "Account", "Other"], name: "Your name", namePlaceholder: "What should we call you?", message: "Message", messagePlaceholder: "Tell us how we can help…", send: "Send message", sending: "Sending…", whatsapp: "Open WhatsApp", success: "Sent successfully!", faq: "Quick questions", questions: [["Does the simulator use live data?", "Prices come from public Binance endpoints; the product remains experimental."], ["Can I export my history?", "Yes. The CSV represents the current manual simulator session."], ["Do you have WhatsApp?", "Use the WhatsApp button beside the form submission button."], ["How can I move to a paid plan?", "Paid plans are in development and cannot be purchased yet."]] },
    simulator: { chart: "Chart", fullscreen: "Full screen" },
  },
  es: {
    plans: { subtitle: "Producto experimental en desarrollo. El modo SIM está disponible; los planes de pago, Testnet y la operación con dinero real no están a la venta en esta fase.", proofs: ["Fase experimental", "SIM disponible", "Sin operación Live"], start: "Empezar gratis", unavailable: "En desarrollo", items: [["LISTO PARA EMPEZAR", "Start", "€ 0,00/mes", ["Simulador spot básico", "Capital virtual de 10.000 USDT", "PNL e historial básico", "Exportar CSV", "8 pares principales habilitados", "Gráfico mensual de equity · próximamente"]], ["RECOMENDADO", "Trader", "€ 9,99/mes", ["Todo en Start", "Robots automáticos (EMA Cross SIM)", "Control de riesgo manual (TP/SL)", "Historial ampliado (visual y CSV)", "Cambio rápido de pares", "Panel resumido de rendimiento · próximamente"]], ["ACELERADO", "Pro", "€ 19,99/mes", ["Todo en Trader", "Gestión automática de riesgo", "Informes detallados con filtros", "Estadísticas avanzadas", "Exportar informes detallados", "Notificaciones de rendimiento · próximamente"]], ["TODO DESBLOQUEADO", "Elite", "€ 29,99/mes", ["Todo en Pro", "Backtesting de estrategias", "Comparación de estrategias", "Historial mensual/anual guardado", "Acceso anticipado a novedades", "Soporte prioritario y comunidad privada"]]] },
    about: { subtitle: "Donde el aprendizaje se une a la práctica — sin arriesgar dinero real, en un entorno virtual seguro y accesible.", pills: ["Producto experimental · modo SIM", "Herramientas para estudiar el mercado"], cards: [["🔒", "Equivócate sin riesgo", "Prueba estrategias con 10.000 USDT virtuales y conoce el mercado sin arriesgar dinero real."], ["🧠", "Aprende de verdad", "Practica la lectura de gráficos y desarrolla disciplina en un entorno experimental."], ["🚀", "Evoluciona siempre", "Revisa resultados, prueba ideas y sigue tu rendimiento con claridad."]], closer: "Entrena hoy. Entiende mañana. Actúa con confianza." },
    contact: { lead: "¿Dudas, sugerencias o colaboración? Escríbenos por el formulario o por WhatsApp.", sendTitle: "Envía un mensaje", subject: "Asunto", topics: ["Duda", "Cuenta", "Otros"], name: "Tu nombre", namePlaceholder: "¿Cómo debemos llamarte?", message: "Mensaje", messagePlaceholder: "Cuéntanos cómo podemos ayudarte…", send: "Enviar mensaje", sending: "Enviando…", whatsapp: "Abrir WhatsApp", success: "¡Enviado correctamente!", faq: "Preguntas rápidas", questions: [["¿El simulador usa datos en vivo?", "Los precios vienen de endpoints públicos de Binance; el producto sigue siendo experimental."], ["¿Puedo exportar mi historial?", "Sí. El CSV representa la sesión actual del simulador manual."], ["¿Tienen WhatsApp?", "Usa el botón de WhatsApp junto al envío del formulario."], ["¿Cómo paso a un plan de pago?", "Los planes de pago están en desarrollo y aún no se pueden contratar."]] },
    simulator: { chart: "Gráfico", fullscreen: "Pantalla completa" },
  },
} as const satisfies Record<Locale, object>;
